title: P2PU & FRSI
description: 'Kluby wiedzy w polskich bibliotekach!


  Dołącz do klubu wiedzy w bibliotece! Przyjdź, spotkaj znajomych, poznaj nowe osoby
  i razem nauczcie się czegoś przydatnego! Spotkania odbywają się raz w tygodniu przez
  6-8 tygodni. Zapraszamy.'
language: pl
